// import { Resolver, Arg, Query } from "type-graphql";
// import { v2 as cloudinary } from "cloudinary";

// cloudinary.config({
//   cloud_name: process.env.CLOUDINARY_CLOUD_NAME,
//   api_key: process.env.CLOUDINARY_API_KEY,
//   api_secret: process.env.CLOUDINARY_API_SECRET,
// });

// @Resolver()
// export class CloudinaryResolcer {
//   @Query()
//   async uploadProfilePicture(
//     @Arg("file", () => File) file: File
//   ): Promise<void> {
//     // const filename = file.name;
//     await cloudinary.uploader.upload(file.name, {}, (err, img) => {
//       console.log();
//       console.log("** File Upload");

//       if (err) {
//         console.warn(err);
//         return false;
//       }

//       console.log(
//         "* public_id for the uploaded image is generated by Cloudinary's service."
//       );

//       if (img) {
//         console.log("* " + img.public_id);
//         console.log("* " + img.url);
//         return true;
//       }

//       return null;
//     });
//   }
// }

export default {}